# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-03 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20170526_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='article',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='voices',
            field=models.IntegerField(default=0),
        ),
    ]
