# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-17 10:16
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('author', models.CharField(default='admin', max_length=20)),
                ('tags', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=250)),
                ('section_priority', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='section_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Section'),
        ),
    ]
