# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-05 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('content', models.TextField(default='Ваш комментарий...')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='tags',
        ),
        migrations.AddField(
            model_name='lesson',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lesson',
            name='rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='voices',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessoncomment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.Lesson'),
        ),
    ]
